### ISSUE TITLE
Error while using transcribe-stream

### ISSUE THREAD

**Issue by arnamoy10** [synesthesiam/voice2json#18]
Hello All, after training the profile following the getting started guide, I am trying to run transcribe-stream, but I am getting the following error:

`ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
arecord: main:828: audio open error: No such file or directory`

What can be the issue?  I have the correct hardware card stored in a `.asoundrc` file.  Is there any other option I can give to voice2json to use the proper audio device?

Thanks

**Comment by johanneskropf** [comment]
Do you use the docker install or the deb package?

**Comment by synesthesiam** [comment]
Make sure to pass `--device /dev/snd:/dev/snd` if using the Docker image.

**Comment by xinkez** [comment]
@synesthesiam Hi, when I tried to run transcribe-stream, I got the following error. What can be this issue? Thank you in advance.

Ready
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xxx/voice2json/voice2json/transcribe.py", line 184, in transcribe_proc
    audio_stream(), sample_rate, sample_width, channels
  File "/home/xxx/voice2json/.venv/lib/python3.7/site-packages/rhasspyasr_pocketsphinx/transcribe.py", line 93, in transcribe_stream
    self.decoder = self.get_decoder()
  File "/home/xxx/voice2json/.venv/lib/python3.7/site-packages/rhasspyasr_pocketsphinx/transcribe.py", line 147, in get_decoder
    decoder = pocketsphinx.Decoder(decoder_config)
  File "/home/xxx/voice2json/.venv/lib/python3.7/site-packages/pocketsphinx/pocketsphinx.py", line 273, in __init__
    this = _pocketsphinx.new_Decoder(*args)
RuntimeError: new_Decoder returned -1

**Comment by synesthesiam** [comment]
I'd expect that kind of error if you haven't downloaded the appropriate profile files, or if they're corrupted.

**Comment by synesthesiam** [comment]
Closing issue due to inactivity. Please re-open if the problem persists.
