### ISSUE TITLE
Number sequence slot not working

### ISSUE THREAD

**Issue by djschwab** [synesthesiam/voice2json#37]
Installed voice2json on Ubuntu 20.04 and tried to run [SetTimer] example. I get the following error message when I try to train:
dave@inspiron:~/python$ voice2json train-profile
WARNING:rhasspynlu.slots:Failed to load file/program for slot rhasspy/number,1,59,1 (tried: [PosixPath('/home/dave/.config/voice2json/slots')], [PosixPath('/home/dave/.config/voice2json/slot_programs')])
WARNING:rhasspynlu.slots:Failed to load file/program for slot rhasspy/number,1,9,1 (tried: [PosixPath('/home/dave/.config/voice2json/slots')], [Poto trainsixPath('/home/dave/.config/voice2json/slot_programs')])
Traceback (most recent call last):
  File "__main__.py", line 6, in <module>
  File "asyncio/runners.py", line 43, in run
  File "asyncio/base_events.py", line 587, in run_until_complete
  File "voice2json/__main__.py", line 73, in main
  File "voice2json/__main__.py", line 745, in train
  File "voice2json/core.py", line 65, in train_profile
  File "voice2json/train.py", line 231, in train_profile
  File "rhasspynlu/jsgf_graph.py", line 426, in sentences_to_graph
  File "rhasspynlu/jsgf_graph.py", line 124, in expression_to_graph
  File "rhasspynlu/jsgf_graph.py", line 194, in expression_to_graph
  File "rhasspynlu/jsgf_graph.py", line 124, in expression_to_graph
  File "rhasspynlu/jsgf_graph.py", line 124, in expression_to_graph
  File "rhasspynlu/jsgf_graph.py", line 124, in expression_to_graph
  File "rhasspynlu/jsgf_graph.py", line 100, in expression_to_graph
  File "rhasspynlu/jsgf_graph.py", line 124, in expression_to_graph
  File "rhasspynlu/jsgf_graph.py", line 194, in expression_to_graph
  File "rhasspynlu/jsgf_graph.py", line 124, in expression_to_graph
  File "rhasspynlu/jsgf_graph.py", line 124, in expression_to_graph
  File "rhasspynlu/jsgf_graph.py", line 124, in expression_to_graph
  File "rhasspynlu/jsgf_graph.py", line 206, in expression_to_graph
AssertionError: Missing slot $rhasspy/number,1,9,1
[12215] Failed to execute script __main__

Any advice?

**Comment by synesthesiam** [comment]
Which profile did you download? The slot program is available here: https://github.com/synesthesiam/en-us_kaldi-zamia/tree/master/slot_programs/rhasspy

Just make sure to copy `number` to `/home/dave/.config/voice2json/slot_programs`

**Comment by djschwab** [comment]
Thanks!
