### ISSUE TITLE
V2.1: error in en-us_pocketsphinx-cmu profile download

### ISSUE THREAD

**Issue by OSS542** [synesthesiam/voice2json#56]
Using en-us_pocketsphinx-cmu for the profile specification results in the following:
bash-3.2$ voice2json --debug --profile en-us_pocketsphinx-cmu download-profile
DEBUG:voice2json:Namespace(profile='en-us_pocketsphinx-cmu', base_directory=PosixPath('/usr/share/voice2json'), certfile=None, keyfile=None, setting=[], machin
e='x86_64', no_auto_download=False, no_auto_train=False, debug=True, command='download-profile', conditions=[], url_format=None, func=<function download_profil
e at 0x7f83b23a7ca0>)
Traceback (most recent call last):
File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/usr/lib/python3.9/site-packages/voice2json/main.py", line 1088, in
asyncio.run(main())
File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
return future.result()
File "/usr/lib/python3.9/site-packages/voice2json/main.py", line 80, in main
await args.func(args)
File "/usr/lib/python3.9/site-packages/voice2json/main.py", line 1013, in download_profile
profile_dir, profile_yaml, profile_name = get_profile_location(args)
File "/usr/lib/python3.9/site-packages/voice2json/main.py", line 608, in get_profile_location
assert profile_dir is not None
AssertionError

**Comment by OSS542** [comment]
note: using en-us_pocketsphinx-cmu for the profile specification results in the following:

bash-3.2$ voice2json --debug --profile en-us_pocketsphinx-cmu download-profile
DEBUG:voice2json:Namespace(profile='en-us_pocketsphinx-cmu', base_directory=PosixPath('/usr/share/voice2json'), certfile=None, keyfile=None, setting=[], machin
e='x86_64', no_auto_download=False, no_auto_train=False, debug=True, command='download-profile', conditions=[], url_format=None, func=<function download_profil
e at 0x7f83b23a7ca0>)
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/voice2json/__main__.py", line 1088, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/site-packages/voice2json/__main__.py", line 80, in main
    await args.func(args)
  File "/usr/lib/python3.9/site-packages/voice2json/__main__.py", line 1013, in download_profile
    profile_dir, profile_yaml, profile_name = get_profile_location(args)
  File "/usr/lib/python3.9/site-packages/voice2json/__main__.py", line 608, in get_profile_location
    assert profile_dir is not None
AssertionError

**Comment by OSS542** [comment]
It would appear that "profile_dir" is not set if the given profile specification is not an existing file or directory.
