### ISSUE TITLE
Could not find a version that satisfies the requirement rhasspynlu (from versions: none)

### ISSUE THREAD

**Issue by gnusupport** [synesthesiam/voice2json#83]
```
./bin/voice2json 
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/data1/protected/Programming/git/voice2json/voice2json/__main__.py", line 26, in <module>
    from .pronounce import pronounce
  File "/home/data1/protected/Programming/git/voice2json/voice2json/pronounce.py", line 15, in <module>
    import rhasspynlu
ModuleNotFoundError: No module named 'rhasspynlu'
/home/admin/Programming/git/voice2json
$ pip install rhasspynlu
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement rhasspynlu (from versions: none)
ERROR: No matching distribution found for rhasspynlu
/home/admin/Programming/git/voice2json
$ 
```

**Comment by synesthesiam** [comment]
[rhasspy-nlu](https://pypi.org/project/rhasspy-nlu/)
